USE CRM;

SET COLLATION_SERVER = LATIN1_SWEDISH_CI;
SET COLLATION_DATABASE = LATIN1_SWEDISH_CI;

INSERT INTO CUSTOMERS(NAME,GENDER,BIRTHDAY,ADDRESS) VALUES('Mary Smith','FEMALE','1967-09-18','No.1283, Queen street, Chicago');

INSERT INTO CUSTOMERS(NAME,GENDER,BIRTHDAY,ADDRESS) VALUES('John Smith','MALE','1965-01-27','No.1283, Queen street, Chicago');

INSERT INTO CUSTOMERS(NAME,GENDER,BIRTHDAY,ADDRESS) VALUES('Tom Smith','MALE','1989-06-03','No.1283, Queen street, Chicago');

INSERT INTO CUSTOMERS(NAME,GENDER,BIRTHDAY,ADDRESS) VALUES('Tony Bush','MALE','1982-11-02','No.858, Washington Street, Suite 103, Bonston');

INSERT INTO CUSTOMERS(NAME,GENDER,BIRTHDAY,ADDRESS) VALUES('Angelina Bush','FEMALE','1983-09-30','No.858, Washington Street, Suite 103, Bonston');

INSERT INTO CUSTOMERS(NAME,GENDER,BIRTHDAY,ADDRESS) VALUES('John Brown',NULL,'1972-07-31','No.405 Lexington Avenue 26th Fl.New York');

SELECT * FROM CUSTOMERS;

INSERT INTO CATEGORIES(NAME) VALUES('Books');
INSERT INTO CATEGORIES(NAME) VALUES('Clothing');
INSERT INTO CATEGORIES(NAME) VALUES('Jewelry');
INSERT INTO CATEGORIES(NAME) VALUES('Electronics');
INSERT INTO CATEGORIES(NAME) VALUES('Cars');

SELECT * FROM CATEGORIES;

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('Ford Focus ST',(SELECT ID FROM CATEGORIES WHERE NAME='Cars' LIMIT 1),16810.00,10,'A perfectly balanced blend of refined engineering and undiluted adrenaline.');

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('Java: A Beginner''s Guide',(SELECT ID FROM CATEGORIES WHERE NAME='Books' LIMIT 1),26.48,1509,'Beginner''s Guides to Java Programming');

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('Architecting the Cloud',(SELECT ID FROM CATEGORIES WHERE NAME='Books' LIMIT 1),36.04,2188,'Design Decisions for Cloud Computing Service Models (SaaS, PaaS, and IaaS)');

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('Hobbies For Men',(SELECT ID FROM CATEGORIES WHERE NAME='Books' LIMIT 1),11.15,1020,'A hobby gives a man freedom to pursue his passions and is an outlet for the facets of life that are not stimulated by career or personal obligations');

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('Calvin Klein Monogram Satchel Top Handle Bag',(SELECT ID FROM CATEGORIES WHERE NAME='Clothing' LIMIT 1),168.00,200,'FREE Shipping, FREE Returns');

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('kate spade new york Hanover Street Charee Top Handle Bag',(SELECT ID FROM CATEGORIES WHERE NAME='Clothing' LIMIT 1),378.00,198,'FREE Shipping, FREE Returns');

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('Suzanne Kalan "Vitrine" White Topaz and Diamond Ring',(SELECT ID FROM CATEGORIES WHERE NAME='Jewelry' LIMIT 1),1560.00,60,'FREE Shipping, FREE Returns');

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('Sorrelli "Golden Shadow" Crystal Linear Antique Silver-Tone Drop Earrings',(SELECT ID FROM CATEGORIES WHERE NAME='Jewelry' LIMIT 1),67.60,125,'FREE Shipping, FREE Returns');

INSERT INTO PRODUCTS(NAME,CATEGORY_ID,PRICE,INVENTORY,DESCRIPTION) VALUES('Kindle Paperwhite',(SELECT ID FROM CATEGORIES WHERE NAME='Electronics' LIMIT 1),119.60,20000,'Unlike tablets, Kindle Paperwhite is designed to deliver the best reading experience');

SELECT * FROM PRODUCTS;

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Tom Smith' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Architecting the Cloud' LIMIT 1),1,3.50,'2014-06-02');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Mary Smith' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Ford Focus ST' LIMIT 1),1,500.00,'2014-06-16');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Angelina Bush' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Suzanne Kalan "Vitrine" White Topaz and Diamond Ring' LIMIT 1),3,150.00,'2014-06-30');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Tom Smith' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Kindle Paperwhite' LIMIT 1),1,27.60,'2014-07-09');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Tony Bush' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Hobbies For Men' LIMIT 1),1,1.15,'2014-07-12');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='John Smith' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Java: A Beginner''s Guide' LIMIT 1),3,10.20,'2014-07-15');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Tom Smith' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Sorrelli "Golden Shadow" Crystal Linear Antique Silver-Tone Drop Earrings' LIMIT 1),2,15.00,'2014-07-24');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Angelina Bush' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Suzanne Kalan "Vitrine" White Topaz and Diamond Ring' LIMIT 1),1,60.00,'2014-08-01');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Mary Smith' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='kate spade new york Hanover Street Charee Top Handle Bag' LIMIT 1),1,28.10,'2014-08-03');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Mary Smith' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Calvin Klein Monogram Satchel Top Handle Bag' LIMIT 1),2,54.90,'2014-08-03');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='Tony Bush' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Kindle Paperwhite' LIMIT 1),1,27.60,'2014-08-18');

INSERT INTO PURCHASES(CUSTOMER_ID,PRODUCT_ID,QUANTITY,DISCOUNT,CREATE_TIME) VALUES((SELECT CUSTOMER_NO FROM CUSTOMERS WHERE NAME='John Smith' LIMIT 1),(SELECT ID FROM PRODUCTS WHERE NAME='Hobbies For Men' LIMIT 1),1,1.15,'2014-09-01');

SELECT * FROM PURCHASES;